# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NPM Package

on:
  push:
    tags:
    - v*

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.17
        registry-url: https://registry.npmjs.org/
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm run build
    - run: pnpm publish --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Create Release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        allowUpdates: true
